site_name: Jovi Sarmiento | Documentation Specialist

theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Home: index.md

  - Portfolio:
      - CardFlow Credit Origination Platform: projects/cardflow-credit-origination-platform/README.md

      - API Documentation: projects/api-documentation/README.md

      - Diagrams: projects/diagrams/README.md

      - Documentation Strategy: projects/documentation-strategy/README.md

      - AI Documentation Automation: projects/ai-documentation-automation/README.md

  - Skills & Tools: skills-tools/README.md

  - Resume: resume/README.md

  - About: about/README.md
