site_name: Jovi Sarmiento | Documentation Specialist

theme:
  name: material
  custom_dir: overrides  
  favicon: assets/images/branding/favicon.svg
  logo: assets/images/branding/logo.svg  
  features:
    - navigation.path    # Displays breadcrumb navigation
    - navigation.footer  # Adds Previous and Next links based on navigation order

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


extra_css:
  - stylesheets/extra.css
  - stylesheets/downloadable-documentation.css
  - stylesheets/saas-ecosystem.css  

extra_javascript:
  - javascripts/navigation-footer.js
  - javascripts/image-lightbox.js
  - javascripts/artifact-navigation.js
  - javascripts/html-toc.js

plugins:
  - search
  - awesome-nav

#nav:
#  - Home: index.md
#
#  - Portfolio:
#      - SaaS Documentation: projects/saas-documentation/README.md
#
#     - API Documentation: projects/api-documentation/README.md
#
#      - Visual Documentation: projects/visual-documentation/README.md
#
#      - Documentation Strategy: projects/documentation-strategy/README.md
#
#      - AI Documentation Automation: projects/ai-documentation-automation/README.md
#
#  - Skills & Tools: more-about-me/skills-tools/README.md
#
#  - More About Me:
#      - Resume: resume/README.md
#
#      - About: about/README.md

extra:
  browser_title: Jovi Sarmiento | Documentation Specialist
