nav:
  - Home: index.md
  - Projects: projects
  - Downloads: downloadable-documentation/README.md
  - More About Me:
      - Professional Experience: more-about-me/professional-experience/README.md
      - Skills & Tools: more-about-me/skills-tools/README.md
      - About My Work: more-about-me/about-my-work/README.md
